site_name: Fab Դպրոց 2026 - Hayk Abrahamyan
site_url: https://haykabrahamyan966-lab.github.io/Hayk_Abrahamyan/

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: grey

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Գլխավոր: index.md
  - Իմ մասին: about/index.md
  - Առաջադրանքներ: assignments/index.md
  - Ավարտական նախագիծ: projects/final-project.md