site_name: Ֆաբ Դպրոց 2026 - Հայկ Աբրահամյան
site_url: https://hayk-abrahamyan.github.io/fablab26/

theme:
  name: material
  language: hy
  palette:
    # Light Mode (Լուսավոր թեմա)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark Mode (Մութ թեմա)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy

  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - About:
      - Bio: about/index.md
      - Student Agreement: about/agreement.md
  - Assignments: assignments/index.md
  - Final Project: projects/final-project.md