site_name: Fab Academy 2026 - Hayk Abrahamyan
site_url: https://haykabrahamyan966-lab.github.io/Hayk_Abrahamyan/

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: grey

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - About:
      - Bio: about/index.md
      - Student Agreement: about/agreement.md
  - Assignments: assignments/index.md
  - Final Project: projects/final-project.md